sudo: required
dist: trusty
language: python

addons:
  apt:
    packages:
      # - thrift-compiler
      - docker


before_install:
  - sudo docker run -d --name mongo -p 27017:27017 mongo:latest
  - docker ps
  - sudo apt-get install -y sqlite
  - sudo apt-get install -y maven
  - sudo apt-get install -y nodejs

  # - install thrift
  - cd ~/
  - wget -q http://archive.apache.org/dist/thrift/0.9.3/thrift-0.9.3.tar.gz &>/dev/null
  - tar -xzf thrift-0.9.3.tar.gz &>/dev/null
  - cd ~/thrift-0.9.3
  - sudo ./configure --without-python --without-java --without-ruby
  - sudo make
  - sudo ln -n ~/thrift-0.9.3/compiler/cpp/thrift /usr/local/bin/thrift


install:

  # do pip installs, set pythonpath
  - pip install -r $TRAVIS_BUILD_DIR/client/python/requirements.txt
  - export PYTHONPATH=$TRAVIS_BUILD_DIR/client/python:$PYTHONPATH

  # gen_sqlite
  - cd $TRAVIS_BUILD_DIR/server/codegen
  - sh ./gen_sqlite.sh

  # clear old modeldb mongodb data and start mongodb server
  - mongo modeldb_metadata --eval "db.dropDatabase()"
  - mkdir -p mongodb
  - mongod --dbpath mongodb &


  # build python client
  - cd $TRAVIS_BUILD_DIR/client/python
  - touch $TRAVIS_BUILD_DIR/build_client.log
  - ./build_client.sh

  # build scala client
  # - cd $TRAVIS_BUILD_DIR/client/scala/libs/spark.ml
  # - ./build_client.sh

  # start server
  # - touch $TRAVIS_BUILD_DIR/server.log
  - cd $TRAVIS_BUILD_DIR/server
  - ./start_server.sh &
  # - ../scripts/gen_thrift_file.py java '../thrift/ModelDB.thrift' './src/main/thrift/'
  # - THRIFT_VERSION="-Dthrift_version=0.9.3"
  # - mvn clean compile $THRIFT_VERSION
  # - mvn exec:java -Dexec.mainClass="edu.mit.csail.db.ml.main.Main" $THRIFT_VERSION &
  - /bin/sleep 40

  # # start frontend
  # - touch $TRAVIS_BUILD_DIR/frontend.log
  # - cd $TRAVIS_BUILD_DIR/frontend
  # - ./start_frontend.sh >> $TRAVIS_BUILD_DIR/frontend.log 2>&1 &





before_script:
  - export PYTHONPATH=$TRAVIS_BUILD_DIR/client/python:$PYTHONPATH
  # - /bin/netstat -tlpn

script:
  - echo ===================
  - cd $TRAVIS_BUILD_DIR/client/python/modeldb/tests/sklearn
  - python --version
  - python -m unittest discover .
  - echo ===================
  # - cat $TRAVIS_BUILD_DIR/frontend.log
  # - cat $TRAVIS_BUILD_DIR/build_client.log
  - cat $TRAVIS_BUILD_DIR/server.log
  # - cat $TRAVIS_BUILD_DIR/gen_sqlite.log
  # - history
  # - cat /home/travis/.travis/job_stages



