sudo: required
dist: trusty
language: python

addons:
  apt:
    packages:
      # - thrift-compiler
      - docker


before_install:
  - sudo docker run -d --name mongo -p 27017:27017 mongo:latest
  - docker ps
  - sudo apt-get install -y sqlite
  - sudo apt-get install -y maven
  - sudo apt-get install -y nodejs

  - install thrift
  - cd ~/
  - wget -q http://archive.apache.org/dist/thrift/0.9.3/thrift-0.9.3.tar.gz &>/dev/null
  - tar -xzf thrift-0.9.3.tar.gz &>/dev/null
  - cd ~/thrift-0.9.3
  - sudo ./configure --without-python --without-java --without-ruby
  - sudo make
  - sudo ln -n ~/thrift-0.9.3/compiler/cpp/thrift /usr/local/bin/thrift


install:

  # do pip installs, set pythonpath
  - pip install -r $TRAVIS_BUILD_DIR/client/python/requirements.txt
  - export PYTHONPATH=$TRAVIS_BUILD_DIR/client/python:$PYTHONPATH

  # gen_sqlite
  - cd $TRAVIS_BUILD_DIR/server/codegen
  - sh ./gen_sqlite.sh

  # clear old modeldb mongodb data and start mongodb server
  - mongo modeldb_metadata --eval "db.dropDatabase()"
  - mkdir -p mongodb
  - mongod --dbpath mongodb &

  # build python client
  - cd $TRAVIS_BUILD_DIR/client/python
  - ./build_client.sh

  # build scala client
  # - cd $TRAVIS_BUILD_DIR/client/scala/libs/spark.ml
  # - ./build_client.sh

  # start server
  - cd $TRAVIS_BUILD_DIR/server
  - ./start_server.sh
  - /bin/sleep 30

  # # start frontend
  # - cd $TRAVIS_BUILD_DIR/frontend
  # - ./start_frontend.sh



before_script:
  - export PYTHONPATH=$TRAVIS_BUILD_DIR/client/python:$PYTHONPATH
  - /bin/netstat -tlpn

script:
  - echo ===================
  - cd $TRAVIS_BUILD_DIR/client/python/modeldb/tests/sklearn
  - python --version
  # - python -m unittest discover .
  - python testProjectCreation.py



